name: Trigger formula update
# based on https://zenn.dev/uzimaru0000/articles/update-brew-tap
on:
  workflow_dispatch:
    inputs:
      formula:
        description: "formula"
        required: true
      version:
        description: "version"
        required: true
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Update formula
        run: |
          file="Formula/${{github.event.inputs.formula}}.rb"
          echo "file = $file"
          ver="${{github.event.inputs.version}}"
          url="$(grep url "$file" | head -1 | sed -e 's/url\|[ \"]//g' | sed -e 's/[0-9]\+.[0-9]\+.[0-9]\+/'"$ver"'/g')"
          echo "new url = $url"
          sha="$(curl -L "$url" | sha256sum -b | awk '{print $1}')"
          echo "sha256 = $sha"
          echo -e "$(head -3 "$file")\n  url \"$url\"\n  sha256 \"$sha\"\n$(tail +6 "$file")" > "$file"
        shell: bash
      - name: Update curl
        run: |
          curl -fL -o Formula/curl-ws.rb https://raw.githubusercontent.com/Homebrew/homebrew-core/refs/heads/master/Formula/c/curl.rb
          patch Formula/curl-ws.rb ./curl-ws.patch
      - name: Update imagemagick
        run: |
          curl -fL -o Formula/imagemagick-no-openmp.rb https://raw.githubusercontent.com/Homebrew/homebrew-core/refs/heads/master/Formula/i/imagemagick.rb
          patch Formula/imagemagick-no-openmp.rb ./imagemagick-no-openmp.patch
      - name: Update ftxui
        run: |
          git clone https://github.com/ArthurSonzogni/FTXUI.git
          ver="$(git -C FTXUI describe --tags | sed 's/^v//')"
          hash="$(git -C FTXUI rev-parse HEAD)"
          rm -rf FTXUI
          ver_short="$(echo "$ver" | $(which sed) -e 's/-\(.*\)-g.*/.\1/')"
          sed -i 's/revision: ".*"/revision: "'"$hash"'"/' Formula/ftxui.rb
          sed -i 's/version ".*"/version "'"$ver"'"/' Formula/ftxui.rb
          sed -i 's/ PROPERTIES VERSION .*)/ PROPERTIES VERSION '"$ver_short"')/' Formula/ftxui.rb
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.REPO_SCOPED_TOKEN }}
          commit-message: 'Update packages'
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: update-package
          branch-suffix: timestamp
          delete-branch: true
          title: '${{ github.event.inputs.formula }} update for ${{ github.event.inputs.version }}'
          body: |
            @${{ github.actor }}
            
            ${{ github.event.inputs.formula }} update for ${{ github.event.inputs.version }}
            